config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       sessions: "users/sessions",
                       confirmations: "users/confirmations",
                       registrations: "users/registrations"
                   }
  resources :feeling_cards

  resources :need_cards

  resources :needs

  resources :feelings

  resources :experiences do
  end

  root 'feelings#new'

end

app/models/feeling.rb
class Feeling < ActiveRecord::Base

  belongs_to :user
  belongs_to :feeling_card
  belongs_to :experience

  has_many :needs, dependent: :destroy

  def self.get_not_finished_feelings(user)
    where(user: user).where(feeling_card_id: nil)
  end

  def self.get_floatings(user)
    where(user: user).where("feeling_card_id is not null").where(experience_id: nil)
  end

  def get_super_categories
    unless super_category
      FeelingCard.get_super_categories
    end
  end

  def get_categories
    if super_category
      FeelingCard.get_categories(super_category)
    end
  end

  def get_feelings
    if category
      FeelingCard.get_feelings(super_category, category)
    end
  end


  def vfeeling
    if feeling_card
      feeling_card.title
    end
  end

  def vfeeling=(card_id)
    #card = FeelingCard.get_card(super_category, category, f)
    if card_id && !card_id.empty?
      self.feeling_card = FeelingCard.find(card_id)
    end
  end
end

app/controllers/feelings_controller.rb
class FeelingsController < ApplicationController
  before_action :set_feeling, only: [:show, :edit, :update, :destroy]

  # GET /feelings
  # GET /feelings.json
  def index
    @feelings = Feeling.where(user: current_user).all
  end

  # GET /feelings/1
  # GET /feelings/1.json
  def show
  end

  # GET /feelings/new
  def new
    notfinished_feelings = Feeling.get_not_finished_feelings(current_user)
    puts "new #{notfinished_feelings.as_json}"
    @super_categories = FeelingCard.get_super_categories
    unless notfinished_feelings.empty?
      @feeling = notfinished_feelings.first
      @categories = @feeling.get_categories
      @feelings = @feeling.get_feelings
    else
      @feeling = Feeling.new
      @is_new = true
    end
  end

  # GET /feelings/1/edit
  def edit
  end

  # POST /feelings
  # POST /feelings.json
  def create
    @feeling = Feeling.new(feeling_params)

    respond_to do |format|
      if @feeling.save
        format.html { redirect_to new_feeling_path }
        #format.js
        format.json { render :show, status: :created, location: @feeling }
      else
        format.html { render :new }
        #format.json { render json: @feeling.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feelings/1
  # PATCH/PUT /feelings/1.json
  def update
    puts "update #{@feeling.as_json} #{updated_params.as_json}"
    respond_to do |format|
      if @feeling.update(updated_params)
        puts "brucep update success"
        #format.html { redirect_to @feeling, notice: 'Feeling was successfully updated.' }
        format.html { redirect_to new_feeling_path }
        format.json { render :show, status: :ok, location: @feeling }
        #format.js
      else
        format.html { render :edit }
        format.json { render json: @feeling.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feelings/1
  # DELETE /feelings/1.json
  def destroy
    @feeling.destroy
    respond_to do |format|
      format.html { redirect_to feelings_url, notice: 'Feeling was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feeling
      @feeling = Feeling.find(params[:id])
    end

    def updated_params
      new_params = feeling_params
      if new_params[:category] != @feeling.category || new_params[:super_category] != @feeling.super_category
        new_params.delete(:vfeeling) if new_params[:vfeeling]
      end
      new_params
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feeling_params
      params.require(:feeling).permit(:feeling_card_id, :super_category, :category, :vfeeling, :experience_id, :note).merge(user_id: current_user.id)
    end
end

app/helpers/feelings_helper.rb
module FeelingsHelper
end

app/views/feelings/_floating_index.html.erb
<% floating_feelings.each do |feeling| %>
    <%= feeling.feeling_card.title %>
    (<%= link_to 'Need', new_need_path(feeling_id: feeling.id)  %>
    <%= link_to 'Del', feeling, method: :delete, data: { confirm: 'Are you sure?' } %>) &rarr;
    <%= render 'needs/mini_index', floating_needs: feeling.needs %>
    <br>
<% end %>

app/views/feelings/_form.html.erb
<%= simple_form_for @feeling do |f| %>

    <br>
    <% if @is_new %>
        <%= f.input :super_category, label: false, collection: @super_categories, as: :radio_buttons %>
    <% else %>
        <br>
        <%= f.input :super_category, label: false, collection: @super_categories, as: :radio_buttons, input_html: {value: f.object.super_category} %>
        <br>
        <h4>어떤 종류의 느낌이야?</h4>
        <%= f.input :category, label: false, collection: @categories, as: :radio_buttons %>

        <% if @feelings %>
            <br>
            <h4>더 자세히 말해줄래?</h4>
            <%= f.input :vfeeling, label: false, collection: @feelings, as: :radio_buttons %>
            <br>
            <h4>좀 더 이야기 할래?</h4>
            <%= f.input :note, label: false, as: :text, input_html: { :rows => 3, :cols => 30 }  %>
            <br>
            <%= f.button :submit %>
        <% end %>
    <% end %>
    <br>
<% end %>

app/views/feelings/_show.html.erb
<%= feeling.feeling_card.title %>
(<%= feeling.note %>)

<% feeling.needs.each do |need| %>
    <br>    &rarr;  <%= render "needs/show", need: need %>
<% end %>

app/views/feelings/edit.html.erb
<h1>Editing feeling</h1>

<%= render 'form' %>

<%= link_to 'Show', @feeling %> |
<%= link_to 'Back', feelings_path %>

app/views/feelings/index.html.erb
<h1>Listing feelings</h1>

<% @feelings.each do |feeling| %>
    <%= distance_of_time_in_words( Time.now, feeling.created_at) %> ago
    <table>
      <tr class="command_row"><td>
        <%= link_to 'Show', feeling %>
        <%= link_to 'Edit', edit_feeling_path(feeling) %>
        <%= link_to 'Destroy', feeling, method: :delete, data: { confirm: 'Are you sure?' } %>
      </td></tr>
      <tr class="content_row"><td>
        <%= feeling.feeling_card.title %>
        (<%= feeling.note %>)
      </td></tr>

      <tr class="content_row"><td>
        <strong>욕구:</strong>
        <% feeling.needs.each do |need| %>
            <%= render 'needs/show', need: need %><br><br>
        <% end %>
      </td></tr>
    </table>
    <br><br>
<% end %>

<%= link_to 'New Feeling', new_feeling_path %>
<br>

app/views/feelings/new.html.erb
<h2>지금 느낌은?</h2>

<%= render 'form' %>

app/views/feelings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Feeling card:</strong>
  <%= @feeling.feeling_card %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @feeling.experience %>
</p>

<p>
  <strong>Note:</strong>
  <%= @feeling.note %>
</p>

<p>
  <strong>Deleted at:</strong>
  <%= @feeling.deleted_at %>
</p>

<%= link_to 'Edit', edit_feeling_path(@feeling) %> |
<%= link_to 'Back', feelings_path %>