config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       sessions: "users/sessions",
                       confirmations: "users/confirmations",
                       registrations: "users/registrations"
                   }
  resources :feeling_cards

  resources :need_cards

  resources :needs

  resources :feelings

  resources :experiences do
  end

  root 'feelings#new'

end

app/models/need_card.rb
class NeedCard < ActiveRecord::Base

  def self.category(c)
    where(category: c)
  end

  def self.card(c, n)
    category(c).where(title: n).first
  end

  def self.get_categories
    all.group_by{|p| p[:category]}.map { |k,v| k}
  end
end

app/controllers/need_cards_controller.rb
class NeedCardsController < ApplicationController
  before_action :set_need_card, only: [:show, :edit, :update, :destroy]

  # GET /need_cards
  # GET /need_cards.json
  def index
    @need_cards = NeedCard.all
  end

  # GET /need_cards/1
  # GET /need_cards/1.json
  def show
  end

  # GET /need_cards/new
  def new
    @need_card = NeedCard.new
  end

  # GET /need_cards/1/edit
  def edit
  end

  # POST /need_cards
  # POST /need_cards.json
  def create
    @need_card = NeedCard.new(need_card_params)

    respond_to do |format|
      if @need_card.save
        format.html { redirect_to @need_card, notice: 'Need card was successfully created.' }
        format.json { render :show, status: :created, location: @need_card }
      else
        format.html { render :new }
        format.json { render json: @need_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /need_cards/1
  # PATCH/PUT /need_cards/1.json
  def update
    respond_to do |format|
      if @need_card.update(need_card_params)
        format.html { redirect_to @need_card, notice: 'Need card was successfully updated.' }
        format.json { render :show, status: :ok, location: @need_card }
      else
        format.html { render :edit }
        format.json { render json: @need_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /need_cards/1
  # DELETE /need_cards/1.json
  def destroy
    @need_card.destroy
    respond_to do |format|
      format.html { redirect_to need_cards_url, notice: 'Need card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_need_card
      @need_card = NeedCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def need_card_params
      params.require(:need_card).permit(:category, :title)
    end
end

app/helpers/need_cards_helper.rb
module NeedCardsHelper
end

app/views/need_cards/_form.html.erb
<%= simple_form_for @need_card do |f| %>

    <%= f.input :category, collection: @categories, as: :radio_buttons %>
    <%= f.input :vfeeling, collection: @categories, as: :radio_buttons %>

    <%= f.input :note %>
    <%= f.button :submit %>
<% end %>

app/views/need_cards/edit.html.erb
<h1>Editing need_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @need_card %> |
<%= link_to 'Back', need_cards_path %>

app/views/need_cards/index.html.erb
<h1>Listing need_cards</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @need_cards.each do |need_card| %>
      <tr>
        <td><%= need_card.category %></td>
        <td><%= need_card.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Need card', new_need_card_path %>

app/views/need_cards/new.html.erb
<h1>New need_card</h1>

<%= render 'form' %>

<%= link_to 'Back', need_cards_path %>

app/views/need_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @need_card.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @need_card.title %>
</p>

<%= link_to 'Edit', edit_need_card_path(@need_card) %> |
<%= link_to 'Back', need_cards_path %>