config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       sessions: "users/sessions",
                       confirmations: "users/confirmations",
                       registrations: "users/registrations"
                   }
  resources :feeling_cards

  resources :need_cards

  resources :needs

  resources :feelings

  resources :experiences do
  end

  root 'feelings#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Nvc" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div id="user_nav">
          <% if user_signed_in? %>
              <strong><%= current_user.email %></strong>.
              <%= link_to 'Edit', edit_user_registration_path %> |
              <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
              <%= link_to "Sign up", new_user_registration_path %> |
              <%= link_to "Login", new_user_session_path %>
          <% end %>
        </div>

        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "느낌", new_feeling_path  %></li>
            <li><%= link_to "정리하기", new_experience_path  %></li>
          </ul>
        </div>
        <div class="floating-feeling container">
          <%= render 'feelings/floating_index', floating_feelings: @floating_feelings %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">History</li>
              <li><%= link_to "Experiences", experiences_path  %></li>
              <li><%= link_to "Feelings", feelings_path  %></li>
              <li><%= link_to "Needs", needs_path  %></li>
              <li class="nav-header">Cards</li>
              <li><%= link_to "Feelings", feeling_cards_path  %></li>
              <li><%= link_to "needs", need_cards_path  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p> JS &copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>